### ISSUE TITLE
Unable to install jekyll on Ubuntu16.04

### ISSUE THREAD

**Issue by ankitdhall** [hemangsk/Gravity#33]
Hello,
I am trying to setup my github page with your theme and am unable to install jekyll on Ubuntu 16.04.
My default compiler is gcc-4.8 if that could be a possible issue.

The error I get looks like the following:
```
sudo gem install jekyll
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.17/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20170118-14003-6ja05m.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
	from /usr/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
	from /usr/lib/ruby/2.3.0/mkmf.rb:657:in `try_ldflags'
	from /usr/lib/ruby/2.3.0/mkmf.rb:1813:in `pkg_config'
	from extconf.rb:15:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.17/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/ffi-1.9.17 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.17/gem_make.out
```

The mkmf.log file contains the following:

```
| pkg-config --libs libffi
=> "-lffi\n"
"gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-2.3.0 -I/usr/include/ruby-2.3.0/ruby/backward -I/usr/include/ruby-2.3.0 -I. -Wdate-time$
gcc: error: unrecognized command line option ‘-Wdate-time’
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

Do you have any idea of how I could setup jekyll on the machine?
Thanks,
Ankit

**Comment by hemangsk** [comment]
Does this help http://stackoverflow.com/a/13767801 ?
After executing the commands in this answer, you can try doing ```sudo gem install jekyll```

**Comment by ankitdhall** [comment]
No, I already have the right version installed for gem.
And I did sudo as well, same result.

**Comment by hemangsk** [comment]
Can you try updating gcc?

**Comment by ankitdhall** [comment]
Yeah, I reverted to gcc-5 and it seems to install.
